export const SORT_MOVIES = 'SORT_MOVIES';
export const SEARCHBY = 'SEARCHBY';
export const SEARCH_PHRASE_CHANGE = 'SEARCH_PHRASE_CHANGE';
export const LOAD_MOVIES = 'LOAD_MOVIES';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_FAILED = 'LOAD_MOVIES_FAILED';