const actionTypes = {
  SORT_MOVIES: 'SORT_MOVIES',
  SEARCHBY: 'SEARCHBY',
  SEARCH_PHRASE_CHANGE: 'SEARCH_PHRASE_CHANGE',
  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_MOVIES_SUCCESS: 'LOAD_MOVIES_SUCCESS',
  LOAD_MOVIES_FAILED: 'LOAD_MOVIES_FAILED',
  PERSIST_LAST_SEARCH_PHRASE: 'PERSIST_LAST_SEARCH_PHRASE',
  RESET_STORE: 'RESET_STORE',
  SELECT_ONE_MOVIE: 'SELECT_ONE_MOVIE',
  LOAD_ONE_MOVIE: 'LOAD_ONE_MOVIE',
  LOAD_ONE_MOVIE_SUCCESS: 'LOAD_ONE_MOVIE_SUCCESS',
  LOAD_ONE_MOVIE_FAILED: 'LOAD_ONE_MOVIE_FAILED',
};

export default actionTypes;
